// <auto-generated />
namespace projeoneritakipsistemi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class versiyon8 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(versiyon8));
        
        string IMigrationMetadata.Id
        {
            get { return "201603201903051_versiyon8"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
